# Generated by Django 5.2.8 on 2026-01-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
