# Generated by Django 5.2.8 on 2026-01-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userlogin_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
